public enum Enum_EmailLoginResult
{
    Null,
    CouldNotResolveAllFirebaseDependincies,
    LoginSuccess,
    LoginFailure,
    RegisterSuccess,
    SignedIn,
    SignedOut,
    AutoLoginSuccess,
    NoUserAutoLoginCanceled,
    EmailIsInvalid,
    EmailOrPasswordIsWrong,
    EmailAlreadyUse,
    UnknownError,
    VerificationCancelled,
    TooManyRequest,
    VerifyEmail
}
